import { IconName } from "@blueprintjs/core";

export const typesToIcons: Record<string, IconName> = {
  integer: "numerical",
  decimal: "numerical",
  range: "horizontal-distribution",
  text: "new-text-box",
  select_one: "select",
  select_multiple: "multi-select",
  select_one_from_file: "select",
  select_multiple_from_file: "multi-select",
  rank: "sort-numerical-desc",
  note: "edit",
  geopoint: "geolocation",
  geotrace: "geofence",
  geoshape: "geofence",
  date: "calendar",
  time: "time",
  datetime: "calendar",
  image: "media",
  audio: "media",
  video: "video",
  file: "media",
  barcode: "barcode",
  calculate: "calculator",
  acknowledge: "circle-arrow-right",
  hidden: "eye-off",
  "xml-external": "tree",
  start: "timeline-events",
  end: "timeline-events",
  today: "calendar",
  deviceid: "id-number",
  simserial: "id-number",
  subscriberid: "id-number",
  phonenumber: "mobile-phone",
  username: "id-number",
  email: "send-message",
  audit: "shield",
  begin_group: "group-objects",
};
