import { IconName } from "@blueprintjs/core";

export const typesToIcons: Record<string, IconName> = {
  integer: "numerical",
  decimal: "numerical",
  range: "horizontal-distribution",
  text: "edit",
  select_one: "selection",
  select_one_from_file: "selection",
  select_multiple: "multi-select",
  select_multiple_from_file: "multi-select",
  rank: "sort-numerical",
  note: "lightbulb",
  geopoint: "geolocation",
  geotrace: "geofence",
  geoshape: "geofence",
  date: "calendar",
  time: "time",
  datetime: "time",
  image: "media",
  audio: "headset",
  video: "video",
  file: "upload",
  barcode: "barcode",
  calculate: "function",
  acknowledge: "switch",
  hidden: "eye-off",
  "xml-external": "layout-hierarchy",
  start: "time",
  end: "time",
  today: "calendar",
  deviceid: "desktop",
  simserial: "sim-card",
  subscriberid: "id-number",
  phonenumber: "phone",
  username: "person",
  email: "envelope",
  audit: "shield",
  begin_group: "group-objects",
  begin_repeat: "repeat",
};

export const fieldTypeNames: Record<string, string> = {
  integer: "Integer number",
  decimal: "Decimal number",
  range: "Range",
  text: "Text field",
  select_one: "Choose one",
  select_one_from_file: "Choose one from file",
  select_multiple: "Multiple choice",
  select_multiple_from_file: "Multiple choice from file",
  rank: "Rank items",
  note: "Note / Hint",
  geopoint: "Locate a point",
  geotrace: "Trace a line",
  geoshape: "Draw a shape",
  date: "Date",
  time: "Time",
  datetime: "Date and time",
  image: "Image",
  audio: "Audio",
  video: "Video",
  file: "File",
  barcode: "Scan a code",
  acknowledge: "Checkbox",
  calculate: "Calculate formula",
  hidden: "Hidden field",
  "xml-external": "External XML reference",
  start: "Survey start date and time",
  end: "Survey submission date and time",
  today: "Survey start day",
  deviceid: "Device ID",
  simserial: "SIM serial number",
  subscriberid: "Subscriber ID",
  phonenumber: "Phone number",
  username: "Username",
  email: "Email address",
  audit: "Audit trail",
  begin_group: "Field group",
  begin_repeat: "Repeat group",
};

export const fieldCategoriesToIcons: Record<string, IconName> = {
  literal: "edit",
  choice: "selection",
  geo: "globe",
  time: "time",
  media: "upload",
  stats: "scatter-plot",
  track: "person",
  special: "small-minus",
  grouping: "layout-hierarchy",
};

export const fieldCategoryNames: Record<string, string> = {
  literal: "Enter value",
  choice: "Choice",
  geo: "Maps",
  time: "Date and time",
  media: "Upload",
  special: "Other",
  stats: "Statistics",
  track: "Personal data",
  grouping: "Grouping",
};

export const fieldTypesToCategories: Record<string, string> = {
  integer: "literal",
  decimal: "literal",
  range: "literal",
  text: "literal",
  barcode: "literal",
  acknowledge: "literal",
  select_one: "choice",
  select_one_from_file: "choice",
  select_multiple: "choice",
  select_multiple_from_file: "choice",
  rank: "choice",
  geopoint: "geo",
  geotrace: "geo",
  geoshape: "geo",
  date: "time",
  time: "time",
  datetime: "time",
  image: "media",
  audio: "media",
  video: "media",
  file: "media",
  note: "special",
  calculate: "special",
  hidden: "special",
  "xml-external": "special",
  start: "stats",
  end: "stats",
  today: "stats",
  deviceid: "track",
  simserial: "track",
  subscriberid: "track",
  phonenumber: "track",
  username: "track",
  email: "track",
  audit: "track",
  begin_group: "grouping",
  begin_repeat: "grouping",
};
